# Generated by Django 4.0.4 on 2022-05-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_ferroviaria', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntored',
            name='linea',
        ),
        migrations.AlterField(
            model_name='eventoeje',
            name='punto_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='red_ferroviaria.puntored'),
        ),
        migrations.DeleteModel(
            name='Linea',
        ),
        migrations.DeleteModel(
            name='PuntoRed',
        ),
    ]
