# Generated by Django 4.0.4 on 2022-07-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_eventoeje_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventovagon',
            name='cambio',
        ),
        migrations.AddField(
            model_name='eventoeje',
            name='tempa',
            field=models.FloatField(blank=True, default=25, null=True),
        ),
        migrations.AddField(
            model_name='eventoeje',
            name='tempb',
            field=models.FloatField(blank=True, default=25, null=True),
        ),
        migrations.AddField(
            model_name='eventoeje',
            name='vel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventovagon',
            name='vel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
