# Generated by Django 4.0.4 on 2022-05-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_ferroviaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntored',
            name='nudo',
            field=models.BooleanField(default=False),
        ),
    ]
