# Generated by Django 4.0.4 on 2022-05-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('anchos', models.CharField(choices=[('UIC-IB', 'UIC(1435) <> IBÉRICO (1668)'), ('UIC-RUS', 'UIC(1435) <> RUSO (1520)'), ('UIC-RUS-IB', 'UIC <> RUSO <> IBÉRICO'), ('METR-UIC', 'MÉTRICO(1000) <> UIC(1435)')], default='UIC-IB', max_length=12)),
                ('rueda', models.CharField(max_length=16)),
                ('cuerpo_eje', models.CharField(max_length=16)),
                ('fecha_aprovacion', models.DateField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.aprovador')),
                ('certificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.certificador')),
                ('diseñador', models.ForeignKey(limit_choices_to={'de_ejes': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.diseñador')),
            ],
        ),
        migrations.CreateModel(
            name='VersionCambiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('anchos', models.CharField(choices=[('UIC-IB', 'UIC(1435) <> IBÉRICO (1668)'), ('UIC-RUS', 'UIC(1435) <> RUSO (1520)'), ('METR-UIC', 'MÉTRICO(1000) <> UIC(1435)')], default='UIC-IB', max_length=12)),
                ('longitud_desencerrojado', models.FloatField(default=6000)),
                ('longitud_cambio_rueda', models.FloatField(default=6000)),
                ('longitud_encerrojado', models.FloatField(default=6000)),
                ('longitud_total', models.FloatField(default=36000)),
                ('fecha_aprovacion', models.DateField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.aprovador')),
                ('certificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.certificador')),
                ('diseñador', models.ForeignKey(limit_choices_to={'de_cambiadores': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.diseñador')),
                ('fabricante', models.ForeignKey(blank=True, limit_choices_to={'de_cambiadores': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
            ],
        ),
    ]
