# Generated by Django 4.0.4 on 2022-05-19 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bogie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('tipo', models.CharField(default=' ', max_length=20)),
                ('foto', models.ImageField(blank=True, upload_to='bogies/')),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('mantenedor', models.ForeignKey(limit_choices_to={'de_bogies': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.mantenedor')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Composicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizaciones.operador')),
            ],
        ),
        migrations.CreateModel(
            name='VersionEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('anchos', models.CharField(choices=[('UIC-IB', 'UIC(1435) <> IBÉRICO (1668)'), ('UIC-RUS', 'UIC(1435) <> RUSO (1520)'), ('UIC-RUS-IB', 'UIC <> RUSO <> IBÉRICO'), ('METR-UIC', 'MÉTRICO(1000) <> UIC(1435)')], default='UIC-IB', max_length=12)),
                ('rueda', models.CharField(max_length=16)),
                ('cuerpo_eje', models.CharField(max_length=16)),
                ('fecha_aprovacion', models.DateField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.aprovador')),
                ('certificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.certificador')),
                ('diseñador', models.ForeignKey(limit_choices_to={'de_ejes': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.diseñador')),
            ],
        ),
        migrations.CreateModel(
            name='VersionCambiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('anchos', models.CharField(choices=[('UIC-IB', 'UIC(1435) <> IBÉRICO (1668)'), ('UIC-RUS', 'UIC(1435) <> RUSO (1520)'), ('METR-UIC', 'MÉTRICO(1000) <> UIC(1435)')], default='UIC-IB', max_length=12)),
                ('longitud_desencerrojado', models.FloatField(default=6000)),
                ('longitud_cambio_rueda', models.FloatField(default=6000)),
                ('longitud_encerrojado', models.FloatField(default=6000)),
                ('longitud_total', models.FloatField(default=36000)),
                ('fecha_aprovacion', models.DateField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.aprovador')),
                ('certificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.certificador')),
                ('diseñador', models.ForeignKey(limit_choices_to={'de_cambiadores': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.diseñador')),
                ('fabricante', models.ForeignKey(blank=True, limit_choices_to={'de_cambiadores': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Vagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('tipo', models.CharField(default=' ', max_length=20)),
                ('descripcion', models.CharField(default=' ', max_length=100)),
                ('num_bogies', models.IntegerField(blank=True, default=2, null=True)),
                ('num_ejes', models.IntegerField(blank=True, default=4, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='vagones/')),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('composicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.composicion')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('mantenedor', models.ForeignKey(blank=True, limit_choices_to={'de_vagones': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.mantenedor')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha_fab', models.DateField(blank=True, null=True)),
                ('num_cambios', models.IntegerField(default=0)),
                ('km', models.FloatField(default=0)),
                ('coef_trabajo', models.FloatField(default=0)),
                ('estado', models.CharField(choices=[('CIRCULANDO', 'CIRCULANDO'), ('PARADO', 'PARADO'), ('MANTENIMIENTO', 'MANTENIMIENTO')], default='PARADO', max_length=15)),
                ('alarma', models.BooleanField(default=False)),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('bogie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.bogie')),
                ('fabricante', models.ForeignKey(limit_choices_to={'de_ejes': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('mantenedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.mantenedor')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.operador')),
                ('vagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.vagon')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='material.versioneje')),
            ],
        ),
        migrations.CreateModel(
            name='Cambiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('nombre', models.CharField(default='Experimental-01', max_length=100)),
                ('fecha_fab', models.DateField(blank=True, null=True)),
                ('num_cambios', models.IntegerField(default=0)),
                ('mantenimiento', models.CharField(max_length=16)),
                ('lng', models.FloatField(default=-4.692)),
                ('lat', models.FloatField(default=37.9246)),
                ('fabricante', models.ForeignKey(limit_choices_to={'de_cambiadores': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
                ('mantenedor', models.ForeignKey(limit_choices_to={'de_cambiadores': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.mantenedor')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='material.versioncambiador')),
            ],
        ),
        migrations.AddField(
            model_name='bogie',
            name='vagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.vagon'),
        ),
    ]
