# Generated by Django 4.0.4 on 2022-05-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioneje',
            name='aprovador',
        ),
        migrations.RemoveField(
            model_name='versioneje',
            name='certificador',
        ),
        migrations.RemoveField(
            model_name='versioneje',
            name='diseñador',
        ),
        migrations.AlterField(
            model_name='cambiador',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.versioncambiador'),
        ),
        migrations.AlterField(
            model_name='eje',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.versioneje'),
        ),
        migrations.DeleteModel(
            name='VersionCambiador',
        ),
        migrations.DeleteModel(
            name='VersionEje',
        ),
    ]
