# Generated by Django 4.0.4 on 2022-05-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial'),
        ('ingenieria', '0001_initial'),
        ('material', '0002_remove_versioneje_aprovador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagon',
            name='alarma_aceleraciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagon',
            name='alarma_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagon',
            name='parado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vagon',
            name='ultimo_evento_circ',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vagon',
            name='ultimo_evento_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cambiador',
            name='fabricante',
            field=models.ForeignKey(blank=True, limit_choices_to={'de_cambiadores': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante'),
        ),
        migrations.AlterField(
            model_name='cambiador',
            name='mantenedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'de_cambiadores': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.mantenedor'),
        ),
        migrations.AlterField(
            model_name='cambiador',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.versioncambiador'),
        ),
        migrations.AlterField(
            model_name='eje',
            name='fabricante',
            field=models.ForeignKey(blank=True, limit_choices_to={'de_ejes': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante'),
        ),
        migrations.AlterField(
            model_name='eje',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper'),
        ),
        migrations.AlterField(
            model_name='eje',
            name='mantenedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.mantenedor'),
        ),
        migrations.AlterField(
            model_name='eje',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.operador'),
        ),
        migrations.AlterField(
            model_name='eje',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.versioneje'),
        ),
    ]
