# Generated by Django 4.0.4 on 2022-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_vagon_alarma_aceleraciones_vagon_alarma_temp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eje',
            old_name='alarma',
            new_name='alarma_aceleraciones',
        ),
        migrations.RemoveField(
            model_name='vagon',
            name='ultimo_evento_circ',
        ),
        migrations.AddField(
            model_name='bogie',
            name='vel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eje',
            name='alarma_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eje',
            name='vel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vagon',
            name='en_nudo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagon',
            name='transmitiendo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagon',
            name='vel',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
