# Generated by Django 4.0.4 on 2022-05-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_rename_alarma_eje_alarma_aceleraciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='tempa',
            field=models.FloatField(blank=True, default=25.0, null=True),
        ),
        migrations.AddField(
            model_name='eje',
            name='tempb',
            field=models.FloatField(blank=True, default=25.0, null=True),
        ),
    ]
