# Generated by Django 4.0.4 on 2022-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_eje_tempa_eje_tempb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagon',
            name='ultimo_evento_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
