# Generated by Django 4.0.4 on 2022-05-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_alter_vagon_ultimo_evento_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vagon',
            old_name='alarma_aceleraciones',
            new_name='alarma',
        ),
        migrations.RemoveField(
            model_name='vagon',
            name='alarma_temp',
        ),
    ]
