# Generated by Django 4.0.4 on 2022-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_rename_alarma_aceleraciones_vagon_alarma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='ultimo_mant',
            field=models.DateField(blank=True, null=True),
        ),
    ]
